// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk2JZr358aCJu7Gg_EigQ9IumZ3urU-Ns',
    appId: '1:134637547892:web:40f68c7ece2576cb767c21',
    messagingSenderId: '134637547892',
    projectId: 'fir-practice-49659',
    authDomain: 'fir-practice-49659.firebaseapp.com',
    storageBucket: 'fir-practice-49659.appspot.com',
    measurementId: 'G-GF038B4CBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw_VWkHNHVuU0eDG4qy3lqK7rE2UEsZUs',
    appId: '1:134637547892:android:f31ab8ab12de7668767c21',
    messagingSenderId: '134637547892',
    projectId: 'fir-practice-49659',
    storageBucket: 'fir-practice-49659.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7d8MtXxm01AZLWz4so4YkQoDRBk2GeKo',
    appId: '1:134637547892:ios:8433d5d88ae4811e767c21',
    messagingSenderId: '134637547892',
    projectId: 'fir-practice-49659',
    storageBucket: 'fir-practice-49659.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

}